image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sdk use java 17.0.4-tem
    command: cd time-master; mvn clean install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Time Master App
    description: Time Master Web Server
    port: 6080
    onOpen: open-preview
