image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -DskipUiTests=true"

stages:
  - build
  - serverSetup
  - test
  - coverage
  # - site

cache:
  paths:
    - .m2/repository/
  key: "$CI_BUILD_REF_NAME"

build:
  stage: build
  script:
    - cd time-master; mvn clean compile $MAVEN_CLI_OPTS

apiServer:
  stage: serverSetup
  script:
    - cd time-master/rest; nohup mvn exec:java &

test:
  stage: test
  needs: ["apiServer"]
  script:
    - cd time-master; mvn test $MAVEN_CLI_OPTS

coverageReport:
  stage: coverage
  needs: ["test"]
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - cd time-master; mvn verify $MAVEN_CLI_OPTS
    - cat coverage/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'

# checkstyleReport:
#   stage: site
#   script:
#     - cd time-master; mvn site $MAVEN_CLI_OPTS
    