image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sdk use java 17.0.4-tem
  - name: Install
    command: |
      cd time-master
      mvn clean install -Dmaven.test.skip=true
  - name: REST API Server
    command: |
      cd time-master/rest
      mvn exec:java
    openMode: split-right
  - name: Build
    command: |
      cd time-master
      gp ports await 8080
      mvn test

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Time Master App
    description: Time Master Web Server
    port: 6080
    onOpen: open-preview
